package communication;

public enum BistroCommand {
    SUBSCRIBER_LOGIN,
    EMPLOYEE_LOGIN,
    REGISTER_MEMBER,
    CREATE_RESERVATION,
    CANCEL_RESERVATION,
    GET_ACTIVE_RESERVATIONS_BY_PHONE,
    GET_RESERVATION_BY_ORDER_NUMBER,
    JOIN_WAITING_LIST,
    LEAVE_WAITING_LIST,
    GET_WAITING_LIST,
    CONFIRM_ARRIVAL,
    GET_BILL,
    PAY_BILL,
    GET_MONTHLY_REPORTS,
    CHANGE_STATUS,
    GET_TABLES,
    CHANGE_TABLE_STATUS,
    CHANGE_TABLE_SIZE,
    ADD_SUBSCRIBER
}
